source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '11.0'
use_frameworks!

target 'SttDictionary' do
  pod 'RxSwift', '~> 4.0'
  pod 'RxAlamofire'
  pod 'Alamofire', '~> 4.7'  
  pod 'SDWebImage', '~> 4.0'
  pod "EasyDi"
  pod 'KeychainSwift', '~> 10.0'
  pod 'AppCenter'
  pod "RxRealm" 
  pod 'RealmSwift'
  pod 'SINQ'
  pod 'AlignedCollectionViewFlowLayout', '~> 1.1'
end
